#!/bin/bash

if [[ "$(pwd)" != "/AmongUs/Cafeteria" ]]; then
  echo "Du musst in der Cafeteria sein um ein EMERGENCY MEETING zu starten!"
  exit 0
fi

if [[ "$(cat /tmp/emergency 2>/dev/null)" == "0" ]]; then
  echo "Du kannst nur einmal ein EMERGENCY MEETING starten!"
  exit 0
fi

echo "1" > /tmp/emergency

sleep 1
echo "$(tput setaf 2)Spieler-1:$(tput sgr 0) Ich war zusammen mit Spieler-2 im Elektrik Raum!"
sleep 1
echo "$(tput setaf 2)Spieler-4:$(tput sgr 0) Wer hat das Meeting gestartet???"
sleep 2
echo "$(tput setaf 2)Spieler-6:$(tput sgr 0) Ich war zusammen mit Spieler-4 in der Cafeteria!"
echo "$(tput setaf 2)Spieler-1:$(tput sgr 0) Ich verdächtige Spieler-9!"
sleep 2
echo "$(tput setaf 2)Spieler-4:$(tput sgr 0) Ich war bei Spieler-9 im Admin!"
sleep 1
echo "$(tput setaf 2)Spieler-5:$(tput sgr 0) Ich war alleine in der Navigation."
sleep 1
echo "$(tput setaf 2)Spieler-2:$(tput sgr 0) Ich habe Spieler-5 nicht gesehen und war auch in der Nähe."
sleep 1
echo "$(tput setaf 2)Spieler-5:$(tput sgr 0) Ich finde Spieler-2 ist verdächtig."
sleep 2
echo "$(tput setaf 2)Spieler-2:$(tput sgr 0) Wieso ich?"
echo "$(tput setaf 2)Spieler-1:$(tput sgr 0) Wieso Spieler-2? Der war doch bei mir."
sleep 1
echo ""
echo "Die Diskussion ist beendet ..."
echo ""

echo "0" > /tmp/emergency