#!/bin/bash

echo 0 > /tmp/reaktor

read -p "Code: " code

correctCode=$(cat /AmongUs/Cafeteria/Admin/Antrieb/Code | sed -n 2p)

if [[ "$code" == "$correctCode" ]]; then
    echo "Der Code ist richtig."
    echo 1 > /tmp/reaktor
else
    echo "Der Code ist falsch. Versuche es erneut und überprüfe ob du den Code richitg eingegeben hast."
fi