#!/bin/bash

progress-bar() {
  local duration=${1}
  already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
  remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
  percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
  clean_line() { printf "\r"; }
  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  clean_line
}

if cat /tmp/download 2>/dev/null | grep 1 > /dev/null; then
  echo "Upload:"
  progress-bar 10
  echo 1 > /tmp/upload
  echo ""
else
  echo "Fehler - Du musst die Informationen zuerst herunterladen!"
fi
